SELECT B.Title, BA.AuthorName
FROM BOOKS B, BOOK_AUTHORS BA
WHERE B.BookID = BA.BookID
;

CREATE PROCEDURE Count_Book_Copies
AS
SELECT COUNT(*)
FROM BOOK_COPIES
WHERE BookID = 1 AND BranchID = (SELECT BranchID FROM LIBRARY_BRANCH WHERE BranchName = 'Sharpstown')
GO
;

CREATE PROCEDURE Get_All_Lost_Tribe
AS
SELECT BranchID, Number_Of_Copies
FROM BOOK_COPIES
WHERE BookID = 1
GO
;

CREATE PROCEDURE No_Books_Out
AS
SELECT B.Name
FROM BORROWER B
WHERE B.CardNo NOT IN (SELECT CardNo FROM BOOK_LOANS)
GO
;
